env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {
  semi: ["error", "never"],
  linebreak-style: ["error", "unix"],
  import/no-named-as-default: 0,
  react/prop-types: 0,
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }],
  no-case-declarations: "error",
}
